server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配提供服务的路由地址
          predicates:
            - Path=/payments/** #断言，路径相匹配的进行路由

        - id: payment_routh2      #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配提供服务的路由地址
          predicates:
            - Path=/payments/lb/**     #断言，路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001test.com:7001/eureka,http://eureka7002test.com:7002/eureka #集群
