server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001test.com:7001/eureka,http://eureka7002test.com:7002/eureka #集群
