server:
  port: 10010
spring:
  application:
    name: test1

zuul:
  routes:
    service-provider:
      path: /payments/**
      url: http://CLOUD-PAYMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
   service-url:
    defaultZone: http://eureka7001test.com:7001/eureka,http://eureka7002test.com:7002/eureka #集群